### PR TITLE
fix game category

### PR DESCRIPTION
**Pull request by jkinney23**
Would you believe the correct filter category for games is actually "game"? :)

### CODE REVIEW

**Comment by ghost** [comment]
@johanmalm Could you perhaps check and include this into jgmenu upstream instead of our downstream here?

**Comment by johanmalm** [comment]
@jkinney23 
Thanks. Great catch.
https://github.com/johanmalm/jgmenu/commit/96129ba2548c1f0ff3e3e1994aca05300084fdf8
I've pushed a fix upstream.

**Comment by ghost** [comment]
@johanmalm Thanks!

@jkinney23 Your patch has been included into the upstream jgmenu repository. Thanks for catching this! It'll be part of the next release in BunsenLabs as well.

**Comment by jkinney23** [comment]
Awesome!  Glad to help :)

**Pull request closed without merging**
